sudo: required
services:
    - docker
language:
    - node_js
node_js:
    - "6.1"
before_script:
    - mv .env-travis .env
script:
    - docker-compose -f docker-compose-test.yml up
after_success:
    - docker-compose down